version: '3.8'

services:
  game-service:
    build:
      context: .
    container_name: game-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--", "node", "app.js"]
    networks:
      - game-network

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: gamingpass
      MYSQL_DATABASE: gamingdb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - game-network

volumes:
  mysql-data:

networks:
  game-network:
